<?php 
  $_links = $this->getLinks();
  $count = 0; 
?>
<?php if (count($_links) > 0):?>
<div class='col-md-12'>
  <ul class='nav nav-pills'>
  <?php foreach($_links as $_link): ?>
    <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
  <?php endforeach; ?>
  </ul>
</div>
<?php endif; ?>

