<div class='cgs-footer text-muted'>
  <div class='container cgs-footer-container'>
    <div class='row'>
      <div class='col-md-9'>
        <div class='row'>
          <div class='col-md-2'>
            <img src='<?php echo $this->getSkinUrl("images/logo_black_footer.png") ?>' />
          </div>
          <div class='col-md-5 slogan'>
            <h6 class='text-muted'>Tactical Ear Gadgets and two-way radio accessories</h6>
          </div>
        </div>
        <div class='row'>
          <?php echo $this->getChildHtml() ?>

          <div class='col-md-12 cgs-copyright'>
            <?php echo $this->getCopyright() ?>
          </div>
        </div>
      </div>
      <div class='col-md-3'>
        <div class='secure-seal pull-right'>
          <!-- (c) 2005, 2009. Authorize.Net is a registered trademark of CyberSource Corporation --><script type="text/javascript" language="javascript">var ANS_customer_id="21447558-5c17-4787-84c2-eaea4a4b4742";</script> <script type="text/javascript" language="javascript" src="//verify.authorize.net/anetseal/seal.js" ></script> <a href="http://www.authorize.net/" id="AuthorizeNetText" target="_blank"></a>
          <img src="<?php echo $this->getSkinUrl("images/godaddy-ssl-logo.png"); ?>" />
        </div>
        <div class='cgs-credit-cards pull-right'>
          <div class='credit-card'>
            <img src='<?php echo $this->getSkinUrl("images/American-Express-32.png") ?>' />
          </div>
          <div class='credit-card'>
            <img src='<?php echo $this->getSkinUrl("images/Discover-32.png") ?>' />
            
          </div>
          <div class='credit-card'>
            <img src='<?php echo $this->getSkinUrl("images/Mastercard-credit-card-32.png") ?>' />
            
          </div>
          <div class='credit-card'>
            <img src='<?php echo $this->getSkinUrl("images/Paypal-32.png") ?>' />
            
          </div>
          <div class='credit-card'>
            <img src='<?php echo $this->getSkinUrl("images/Visa-32.png") ?>' />
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
