<nav class='navbar navbar-default navbar-inverse navbar-fixed-top cgs-top-nav' role='navigation'>

  <div class='navbar-header'>
    <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-ex1-collapse'>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class='navbar-brand' href='#'>FREE SHIPPING on orders over $150</a>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <?php echo $this->getChildHtml('topLinks') ?>
    <ul class='nav navbar-nav pull-right hidden-xs'>
      <li class='dropdown'>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Support <b class="caret"></b></a>
        <ul class='dropdown-menu' role='menu'>
          <li><a href="#">Email Us</a></li>
          <li><a onclick="return;">Phone: (818) 433-6949</a></li>
        </ul>
      </li>
      <li class='hide'><a href='#' id='topCChart'>Connector Chart <span class='glyphicon glyphicon-chevron-right'></span></a></li>
    </ul>
    <?php echo $this->getChildHtml('topCart') ?>
  </div>
</nav>